export const KNOWLEDGE_EMBEDDING_PROVIDER = Symbol(
  'KNOWLEDGE_EMBEDDING_PROVIDER',
);

export const KNOWLEDGE_RESULT_LIMIT = 4;
export const KNOWLEDGE_CHUNK_CHARACTER_LIMIT = 1_200;
export const LOCAL_EMBEDDING_MODEL = 'local-hash-v3';
export const LOCAL_EMBEDDING_DIMENSIONS = 384;
